### ISSUE TITLE
Is this SOSA-OMS alignment normative?

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#157]
The SOSA-OMS alignment is currently classed as 'normative' in the draft Recommendation document. 
While we know that the intention is for SOSA to provide a 'canonical' RDF implementation for OMS, who should actually own this? 

W3C probably not. 

If OGC owns it, then is it 
- the SDW SWG ("the SDW SWG asserts that SOSA is the normative RDF implementation of OMS"), 
- or the OMS SWG ("the OMS SWG adopts SOSA as the normative RDF implementation of OMS") ? 
If the latter, then the clause here should be classed "non-normative" and a separate doc from the OMS SWG may be needed. 

Or is it ISO/TC 211?

**Comment by sgrellet** [comment]
During the OM -> OMS revision we asked to have OMS conceptual model as an ontology. We were answered to stick to UML.
So, unless, recommendations from TC211 change since then, I'd say that ISO/TC211 won't be the owner

As for the other options, can't we from the OGC policies point of view, have a co-owned normative alignment between SDW & OMS SWGs ? Afterall @KathiSchleidt  (OMS SWG co-chair), @hylkevds (one of the last 4 finalizing OMS) and myself (OMS SWG co-chair) are involved in both activities.

I'm afraid having a separate doc will scatter the information around which does not help fostering adoption of standards.

**Comment by dr-shorthair** [comment]
A potential difficulty from the W3C position is the need for evidence-of-implementation for all normative content. 
In particular, there are a number of new terms in the `sosa-oms:` namespace, for which we would need implementation evidence by April ...

**Comment by dr-shorthair** [comment]
Note that the modules in 'Horizontal Segmentation' including SSN-SYSTEM were specified to be non-normative partly because of lack of usage data - see https://w3c.github.io/sdw/ssn-usage/#analysis-datasets and https://w3c.github.io/sdw/ssn-usage/#analysis-ontologies

**Comment by dr-shorthair** [comment]
I will mark the alignment as a whole 'normative' but those individual terms that have not been implemented in any known system 'non-normative' - OK?

**Comment by sgrellet** [comment]
Fine with me.
Could we just add a mention somewhere stating : 'non-informative (awaiting proof of implementation)' so that people understand why ?

**Comment by dr-shorthair** [comment]
Completed by aba2745
