### ISSUE TITLE
Missing SamplingCollection

### ISSUE THREAD

**Issue by alexrobin** [w3c/sdw-sosa-ssn#189]
I noticed that we have added `ObservationCollection`, `ActuationCollection` and `SampleCollection` to SOSA.

But the actual equivalent of `ObservationCollection` and `ActuationCollection` in the sampling module would be `SamplingCollection`.

While `SampleCollection` is also useful, I was wondering if the omission of `SamplingCollection` was intentional.

**Comment by dr-shorthair** [comment]
Yes - this was intentional. 
The mismatch was discussed here: https://github.com/w3c/sdw-sosa-ssn/issues/51#issuecomment-1738334326 etc. 

The choices of new classes were based on articulated requirements. 
No-one asked for SamplingCollection and it is less obvious that it would be used. 
As you know, ActuationCollection was only introduced recently in response to your use-cases. 

I recognise that there is a gap that symmetry suggests could be filled. 
OTOH it could also be argued that Sampling is a subclass of Actuation, so perhaps that conversation should be had first.

**Comment by ashleysommer** [comment]
@dr-shorthair 
I've come across this same issue, I need to use a `SamplingCollection` to group a few hundred thousand `Sampling` instances with common properties (same `usedProcedure`, same `hasFeatureOfInterest`, etc). 

As `Observation` and `Sampling` are both actions, the use case would be exactly the same as how `ObservationCollection` is used, simply reducing the number of triples in a Graph by hoisting common properties to the collection level. I agree with the final comments in #51, it seems like when creating `SampleCollection` there was a missed opportunity because `SampleCollection` is at the level of `ResultCollection`, and `SamplingCollection` should have been created as sample-counterpoint to `ObservationCollection`.

In the absence of  `SamplingCollection`, what is the recommend method to achieve this result?

**Comment by dr-shorthair** [comment]
> No-one asked for SamplingCollection and it is less obvious that it would be used.

Now it looks like @ashleysommer is asking. Good. (I hope he can also provide 'evidence of implementation' in support ;-) )

To start the process of also adding `SamplingCollection` please branch/fork and make a PR. 
At a minimum, the following files will need changing:

- /ssn/rdf/ontology/core/sosa-sampling.ttl
- /ssn/rdf/ontology/core/ssn-sampling.ttl
- /ssn/chapters/Sampling.html
- /ssn/index.html
- /ssn/images/Sampling.png
- /ssn/images/Collections.png

**Comment by dr-shorthair** [comment]
@ashleysommer could you prepare a PR to address this?

**Comment by ashleysommer** [comment]
Thanks for your response @dr-shorthair
Yes, I definitely intend to submit a PR for this, I just need to find the time this week to get it written up.

In regard to 'evidence of implementation', what does that look like? Is it an example usecase of how we'd like to apply `SamplingCollection` in our datasets, or would it be something like a PR to include the `SamplingCollection` profiled in the TERN Observations Ontology?

**Comment by dr-shorthair** [comment]
The latter would suffice.

**Comment by ashleysommer** [comment]
@dr-shorthair 
~I notice as part of the introduction of `SampleCollection` it was decided it could include properties of both `Sample` and `Sampling`, that seems a bit odd to me (notably `hasSampledFeature` and `hasOriginalSample`) see attached image.~

~Should these be removed from `SampleCollection` with the introduction of `SamplingCollection` as the intention is `SamplingCollection` will capture properties from `Sampling`?~

![image](https://github.com/w3c/sdw-sosa-ssn/assets/402468/cac4ee97-9615-4432-af28-132f84d5b49d)


EDIT: Actually, perhaps I got it around the wrong way, that image is incorrect because it doesn't match the `domainIncludes` of `hasSampledFeature` and `hasOriginalSample` in the ontology, or in the [Sampling.html](https://github.com/w3c/sdw-sosa-ssn/blob/ecb52b1e5f4bfa84566dc96de767dc25105450d9/ssn/chapters/Sampling.html)


```
sosa:hasOriginalSample 
  a owl:ObjectProperty ;
  rdfs:label "has original sample"@en ;
  skos:definition """
  Link to the original sample collected from the ultimate feature of interest that is related to the context Sample or SampleCollection through a chain of isSampleOf relations.
  """@en ;
  schema:domainIncludes sosa:Sample ;
  schema:domainIncludes sosa:SampleCollection ;
  schema:rangeIncludes sosa:Sample ;
  rdfs:isDefinedBy sosa-sam: .

sosa:hasSampledFeature 
  a owl:ObjectProperty ;
  rdfs:label "has ultimate sampled feature"@en ;
  skos:definition """
  Link to the ultimate feature of interest of the context Sample or SampleCollection - i.e. the end of a chain of isSampleOf relations
  """@en ;
  schema:domainIncludes sosa:Sample ;
  schema:domainIncludes sosa:SampleCollection ;
  schema:rangeIncludes sosa:FeatureOfInterest ;
  rdfs:isDefinedBy sosa-sam: .

```

**Comment by dr-shorthair** [comment]
Well spotted @ashleysommer
These direct links are judged to be useful on a `SampleCollection`. 
But it would be more consistent to change `hasSampledFeature`, `hasOriginalSample` to `isResultOfhasSampledFeature`, `isResultOfhasOriginalSample` in this context, to be consistent with `isResultOfMadeBySampler`, `isResultOfUsedProcedure` - they are effectively property-chains so can be named as such. 

(I spotted it myself a few weeks ago and was wondering if anyone else would ...)

**Comment by dr-shorthair** [comment]
Yes - you are correct. The diagram is wrong. 
The original proposal was here https://www.w3.org/TR/vocab-ssn-ext/#ultimate-feature-of-interest Figure 2. 
I think this would be the correct diagram? 

![Sampling](https://github.com/w3c/sdw-sosa-ssn/assets/608303/de3ed91b-1ce7-4699-8c00-317722d234ae)

**Comment by ashleysommer** [comment]
Yep, that revised diagram looks correct to me.
Where is the source file for that diagram? It would be good to be able to add `SamplingCollection` to it for the PR.

**Comment by dr-shorthair** [comment]
I sent you a link. 
Suggest adding SamplingCollection in upper right, in common with Actuation and Observation diagrams.

**Comment by ashleysommer** [comment]
Okay, I got the link, thanks Simon.

**Comment by ashleysommer** [comment]
It looks like both the `ObservationCollection` and `ActuationCollection` are on the upper _left_ of their respective diagrams, so I've done the same for `SamplingCollection`. How does this look?:
![Sampling](https://github.com/w3c/sdw-sosa-ssn/assets/402468/0c59cb96-5ff9-47c5-840f-8460f150fd10)

**Comment by dr-shorthair** [comment]
You are right. Mild dyslexia strikes again

**Comment by ashleysommer** [comment]
Here's the work-in-progress Collections diagram, will be submitted with the PR:
![Collections(1)](https://github.com/w3c/sdw-sosa-ssn/assets/402468/1a694564-569a-44e9-abd8-9918cacee159)


Another thing I noticed, it looks like in the Observations diagram and the Actuation diagram (and the Collections diagram), ObservationCollection has `hasResult` but not `hasSimpleResult`, and `ActuationCollection` has neither `hasResult` nor `hasSimpleResult` but in the ontology files both collections have `hasResult` and `hasSimpleResult`.

**Comment by dr-shorthair** [comment]
@ashleysommer would you be available to give a briefing on your proposal at a Wednesday evening telecon? 
People are interested to hear your use-case.

**Comment by dr-shorthair** [comment]
In the discussion on 2024-07-31 it was suggested that an (abstract) ExecutionCollection class be added as a superclass of Actuation/Observation/Sampling-Collection. 
I've added this in https://github.com/w3c/sdw-sosa-ssn/tree/samplingcollection where I also merged the changes since @ashleysommer forked his copy. 
I've also checked the properties of all the collection classes for consistency, and updated the diagrams to match. 

See https://github.com/w3c/sdw-sosa-ssn/blob/samplingcollection/ssn/images/Collections.png
