### ISSUE TITLE
Rethink split of OMS vs SOSA

### ISSUE THREAD

**Issue by KathiSchleidt** [w3c/sdw-sosa-ssn#242]
On the one side, we say that SOSA is the semantic representation of OMS, on the other side, we've split a lot of OMS concepts out to the OMS extension of SOSA. The worry is that many people will only take core SOSA onboard, bypass the OMS extensions, begging the question if SOSA is the representation of OMS or not.

We've recently discussed validTime, would like to pull this into SOSA core. Same applies to observationType, as this may be quite valuable in aligning APIs (e.g. STA) to SOSA despite different design patterns (in some scenarios, STA:Datastream -> OMS: ObservationCollection, STA:Observation -> OMS:Observation. In other scenarios, STA:Datastream ->  OMS:Observation, STA:Observation -> OMS:Observation.result)

In addition, if we do the alignment between STA and SOSA, we'll have far more implementation examples

**Comment by dr-shorthair** [comment]
> we say that SOSA is the semantic representation of OMS

No, we don't. SOSA is **not** the representation of OMS. 
We say that the **_SSN Ontology_** provides an RDF implementation. 
See the Section 1. para 6 
"This new edition of the SSN Ontology is primarily intended to align with OMS, so that SSN may serve as the canonical RDF implementation of OMS."

In Section 4. "Modularization" we explicitly point to SOSA-OMS and SSN-OMS: https://w3c.github.io/sdw-sosa-ssn/ssn/#sosa-oms-module

This is repeated in Section 7 "Alignments": 
https://w3c.github.io/sdw-sosa-ssn/ssn/#sosa-oms 
https://w3c.github.io/sdw-sosa-ssn/ssn/#ssn-oms

These are the sections in the document that explicitly deal with the matter of the RDF implementation of OMS. 
I don't know how else we could, or should, deal with people who 'only take core SOSA onboard'.

**Comment by sgrellet** [comment]
I tend to agree with @dr-shorthair here.

We provide the alignment with OMS, and various hints that people could go further than SOSA core.

What do you have in mind here ? add more OMS to SOSA core ?

**Comment by rob-metalinkage** [comment]
#241 explicitly calls out inconsistency in descriptions that is resolved by moving validTime to sosa.  All that is needed is the implementation evidence.   IMHO a SensorThings API mapping to SOSA is executable (using JSON-LD) it would qualify as an implementation, whereas a document describing relationships wouldnt.  I'd start by seeing what the gap looks like.

**Comment by dr-shorthair** [comment]
The `validTime` inconsistency was resolved in the recent merge. 
It is only mentioned in the context of the OMS alignment. 
Please look at https://w3c.github.io/sdw-sosa-ssn/ssn/ to verify.

**Comment by dr-shorthair** [comment]
Some of the confusion may be arising from the term '_alignment_' in the context of the SOSA-OMS mapping. 

There are a set of terms that we are adding which are in OMS but not in core SOSA. 
We are putting them in the `sosa-oms:` namespace. So this looks more like an _extension_. 

Perhaps the RDF implementation of OMS should be described as a SSN Extension, and moved from chapter 7 to chapter 6 (and the diagrams in chapter 4 'Modularization') adjusted to match. 
i.e. no actual change to normative content or packaging, but maybe a better way to conceptualize what `sosa-oms:` is all about? 

(This is result of a conversation with @rob-metalinkage.)

**Comment by dr-shorthair** [comment]
Telecon 2024-09-25 agreed with approach to move OMS implementation to be an SSN Extension (Chapter 6)
