### ISSUE TITLE
How do we indicate the FoI being Observed by a Sensor?

### ISSUE THREAD

**Issue by KathiSchleidt** [w3c/sdw-sosa-ssn#253]
How do we indicate the FoI being Observed by a Sensor?

If we use an FoI-specific Property (PropertyOfInterest), we can state that the Sensor observes this PropertyOfInterest, that is in turn linked to the FoI.

However, if we use a neutral ObservableProperty, there is no direct way to indicate this link. The current workaround seems to be creating a specialization of Observation for this purpose. If this is a common use case, we may want to add this to SOSA, align with the ObservingCapability class from OMS

**Comment by maximelefrancois86** [comment]
What about using `sosa:observes` to also link the Sensor to the FoI ?  that is: including FoI to the range of `sosa:observes`.
That's what we decided to do with https://saref.etsi.org/core/observes

**Comment by sgrellet** [comment]
> How do we indicate the FoI being Observed by a Sensor?

Especially when no observation is created yet ... => that's why we created ObservingCapability in OMS (actually in INSPIRE:EF and moving it to OMS)

> sosa:observes

the point raised by Kathi is that we see many Environmental Monitoring Use Case in Europe where you need to know more : the uFoI, the ObsProperty, the procedure etc... thus the ObservingCapability  in OMS (https://docs.ogc.org/as/20-082r4/20-082r4.html#_observingcapability)

**Comment by dr-shorthair** [comment]
Easy: `sosa:hasFeatureOfInterest` points to the FoI. 
There is no restriction that prevents its domain including `sosa:Sensor` (or any `sosa:System` for that matter). 
We can add `schema:domainIncludes sosa:System` to SOSA to resolve this issue I think. 

`sosa:hasFeatureOfInterest` can sit alongside the `sosa:observes` property (sub-property of `sosa:forProperty`) to fully say what a specific sensor instance is looking at.

**Comment by dr-shorthair** [comment]
Proposed fix 
https://raw.githack.com/w3c/sdw-sosa-ssn/253-foi-on-system/ssn/index.html#Systems-and-their-Deployment-overview 
https://raw.githack.com/w3c/sdw-sosa-ssn/253-foi-on-system/ssn/index.html#SOSASystem 
https://raw.githack.com/w3c/sdw-sosa-ssn/253-foi-on-system/ssn/index.html#SOSAhasFeatureOfInterest
https://raw.githack.com/w3c/sdw-sosa-ssn/253-foi-on-system/ssn/index.html#SOSAisFeatureOfInterestOf

**No new properties**. Just supplementing the domainIncludes and rangeIncludes of existing properties hasFeatureOfInterest and isFeatureOfInterestOf

**Comment by dr-shorthair** [comment]
Telecon discussion suggests that adding `hasFeatureOfInterest` to a Sensor instance would risk problems. The same sensor is likely to be used on multiple FoI. 

The link from a Sensor to a FoI is a _deployment_ related issue. 
https://w3c.github.io/sdw-sosa-ssn/ssn/#Systems-and-their-Deployment-overview 

More helpful might be to add 
(i) `hasFeatureOfInterest` to `Deployment` (or something similar)
(ii) add timing to `Deployment` - startTime/endTime

We need stronger examples/patterns of deployments to show how to do this.

**Comment by dr-shorthair** [comment]
> What about using `sosa:observes` to also link the Sensor to the FoI ? 

`sosa:observes` has the wrong range. See https://w3c.github.io/sdw-sosa-ssn/ssn/#SOSAobserves

**Comment by alexrobin** [comment]
@dr-shorthair I totally agree that associating an FoI to a sensor is a deployment related issue. The association can also be created via an Observation, but it is often useful to also associate an FoI at the deployment level because very often some kind of FoI is known ahead of time (i.e. before any obs are produced).

This is especially true for static in-situ sensors, but it can also be used to identify a larger FoI for mobile or remote sensors. For example, the sample/proximate FoI for a photo taken by a drone may be the exact image footprint (this would be associated to the observation), but often a less specific FoI can also be associated to the deployment (e.g. a specific area, building or other object such as a bridge, etc. that is of interest for a particular mission/deployment. This would often be the sampled feature / ultimate feature of interest, but it can also be a sample itself, e.g. a specific portion of a river that the drone is deployed over).

So what you propose (adding `hasFeatureOfInterest` and `time` to `Deployment`) aligns very well with what we have done in Connected Systems

**Comment by dr-shorthair** [comment]
Like this: 

![Image](https://github.com/user-attachments/assets/d2d42cc2-64b3-4fc4-a50c-6215da4e5924)

**Comment by dr-shorthair** [comment]
2024-11-13 Telecon generally likes this approach, which expands domain of `hasFeatureOfInterest` 

`Deployment` does not have to involve a `Platform`

@ldesousa notes that a `Deployment` always involves a `System`, so perhaps the `forProperty` property should not be associated with `Deployment`

**Comment by KathiSchleidt** [comment]
Opens interesting options:
- I can indicate that a `System `pertains to a specific `FoI`, don't need to provide a `Platform`
- Alternatively, I could also indicate that all `Systems `on a `Platform `are concerned with a specific `FoI `without ever providing the actual `Systems`

**Comment by dr-shorthair** [comment]
Proposed fix
https://raw.githack.com/w3c/sdw-sosa-ssn/253-foi-on-deployment/ssn/index.html#Systems-and-their-Deployment-overview
https://raw.githack.com/w3c/sdw-sosa-ssn/253-foi-on-deployment/ssn/index.html#SOSASystem
https://raw.githack.com/w3c/sdw-sosa-ssn/253-foi-on-deployment/ssn/index.html#SOSAhasFeatureOfInterest
https://raw.githack.com/w3c/sdw-sosa-ssn/253-foi-on-deployment/ssn/index.html#SOSAisFeatureOfInterestOf 
https://raw.githack.com/w3c/sdw-sosa-ssn/253-foi-on-deployment/ssn/index.html#SOSAendTime

One new property, `endTime`, which is super-property of `resultTime`: applies to generic `Execution`, `Deployment`, and to `Actuation`. 
Supplement the `domainIncludes` and `rangeIncludes` of existing properties `hasFeatureOfInterest` and `isFeatureOfInterestOf`

![Image](https://github.com/user-attachments/assets/47fd170c-5e59-4ee1-b677-85c722072c03)

**Comment by dr-shorthair** [comment]
@alexrobin [commented](https://github.com/w3c/sdw-sosa-ssn/pull/264#issuecomment-2485063402)

> @dr-shorthair looks good to me.
>
>However, thinking about it, perhaps it's still useful to add System to the domain of hasFeatureOfInterest as well.
>
>I can see that in the following cases:
>
>Somebody may just want to avoid the complexity of describing deployments because the system is always going to be in the same place.
>
>Some (sampling) FOIs are intrinsically attached to the system (e.g. a camera frustum, as it is usually defined relative to the camera frame).

We discussed this in the telecon. The proposition was that the most common and logical case is for the association of a sensor/actuator/sampler with a FoI is in the context of a deployment. We agreed that interoperability is best served by reducing the alternatives, so the basic pattern is
- `hasFeatureOfInterest` is associated with `Deployment` and `Execution` (time-bounded things)
- `forProperty` is associated with `Procedure`, `Sensor` and `Actuator` (re-usable things)

Your second case (camera frustum) does appear to be a special case, because the proximate feature of interest (the frustum) is tied to the sensor. However, most physical sensors have a similar proximate FoI if we dig deep enough (e.g. temperature sensors sense the volume surrounding the active element), but it is not usually considered interesting enough to describe explicitly. I'm not in the business of describing optical sensors, so am curious about how significant this is in practice. I'm reluctant to modify the general pattern for a lonely case, but perhaps would suggest that this could be managed in the System Capabilities extension (see #230 and #233) rather than in the core ontology. 

Of course the `schema:domainIncludes` axioms are soft, so you would not violate any real constraints by using `hasFeatureOfInterest` on a `Sensor`, but I think we should guide users towards the `Deployment` pattern in general.

**Comment by dr-shorthair** [comment]
I've added a note on System drawing attention to the standard ways to associate one with a FoI - see https://raw.githack.com/w3c/sdw-sosa-ssn/253-foi-on-deployment/ssn/index.html#SOSASystem

**Comment by alexrobin** [comment]
@dr-shorthair Sampling volumes are quite important for any remote sensor, anytime you have to deal with low level data. Cameras have frustums, radars have lobes, etc. But I agree that it could be part of the sensor characteristics package.

I'm ok keeping it this way, especially if adding `hasFeatureInterest` property to a `System` is not forbidden by the ontology.

**Comment by KathiSchleidt** [comment]
Getting back to my initial question of if we shouldn't just add the ObservingCapability class from OMS? As the ObservingCapability represents a potential Observation, I think adding this concept would make sense.

In addition, it would solve the problem of linking a Sensor to an FoI (or anything else Observation relevant).

As for proof of implementation, ObservingCapability comes from INSPIRE, is an integral part of European Air Quality reporting (admittedly not semantically marked up yet, just SOS & STA, but that can be easily done.

**Comment by sgrellet** [comment]
@KathiSchleidt was exactly the discussion of today's webconf . 

from 20241124, meeting notes
_Discussion on the issue, and potential help of OMS:ObservingCapability to this. Using examples from running OGC WaterQuality Interoperability Experiment - Object Diagrams 
one in-situ groundwater example  : https://umltool.ogc.org/index.php?m=7&o=D6BCAD67-7C0F-4898-B819-692B2E514AFA
one ex-situ surface water example : https://umltool.ogc.org/index.php?m=7&o=516F5DFC-6930-44bd-95B0-53F6EBB9281A_

**Comment by dr-shorthair** [comment]
`ObservingCapability` is a big class with a lot of side effects on the overall model. 
In my opinion it would be very disruptive to attempt to introduce it now. 
SSN/SOSA is a more abstract model overall with many fewer classes than OMS. 

Prior work such as OGC WQ IE provide a rich set of requirements and demonstrates some specific solutions using OMS. 

But I don't think that yesterday's discussion uncovered any requirements that could not be met through a combination of the Deployment, Platform, System (Sampler, Sensor) classes from SSN/SOSA.

**Comment by hylkevds** [comment]
> SSN/SOSA is a more abstract model overall with many fewer classes than OMS.

Isn't SSN/SOSA  supposed to be an implementation of OMS? How can an implementation ever be more abstract than the abstract model it implements?

**Comment by dr-shorthair** [comment]
Not exactly. 

SSN/SOSA is a stand-alone ontology. 
The 2017 edition was strongly influenced by O&M but (i) added Sampling and Actuation (ii) added Stimulus, Deployment, Platform, ultimateFeatureOfInterest and a few other details, and (iii) renamed some terms. 

OMS revised O&M and adopted some, but not all, of these additions - for example it doesn't include Actuation. 

The current revision of SSN/SOSA is intended to better align with OMS, and to provide 'an RDF implementation' of OMS. 
But it also must not break any existing implementations that use SSN/SOSA - i.e. it must be 'backward compatible'. 
This means that some terms in SSN/SOSA that have different names to classes or properties in OMS will continue to mismatch - for example: `sosa:Sensor` matches OMS `Observer`. `sosa:hasFeatureOfInterest` matches OMS `proximateFeatureOfInterest`, and `sosa:Platform` matches OMS `Host`. 
This is all explained in https://w3c.github.io/sdw-sosa-ssn/ssn/#OMS-Class-OMS etc. 

So what does 'an RDF implementation' of OMS mean? 
For most of the OMS model there is a 1:1 correspondence with SSN/SOSA, modulo a few term differences. 
But in some areas OMS takes a rather different approach to that which had been established in SSN/SOSA. 
In the case we are looking at here, the OMS class `ObservingCapability` has no direct match in SSN/SOSA. 

So let's look at the chapter where we describe the 'RDF Implementation of OMS' - https://w3c.github.io/sdw-sosa-ssn/ssn/#OMS. 
Most of the this merely lists the correspondence between SSN/SOSA terms and OMS terms. 
Then some new classes and properties are added in a separate namespace `sosa-oms:` which extends the SSN/SOSA core. 
The tabulations in https://w3c.github.io/sdw-sosa-ssn/ssn/#OMS-Class-SOSA etc define the 'RDF Implementation of OMS'. 
If you look there, you will see that the implementation is 'incomplete': not every class from OMS has a match. 
One of the classes that is _not_ matched is `ObservingCapability`. 
So what do we do about that? 

One option is to add `ObservingCapability` to SSN/SOSA core. 
I would oppose that as it disrupts the existing SSN/SOSA design, and is only required for literal OMS conformance, which is not the design goal of SSN/SOSA. 
It is also important to note that the RDF implementation of OMS is an _extension_ to the core of SSN/SOSA. 

So the second option is to add `ObservingCapability` on the `sosa-oms:` namespace. That would require some ontology design, possibly some additional properties and other terms. If one of the OMS team is game to take that on, then maybe fine ... but I truly don't have time to do that. 

A third option is to show how the requirements of `ObservingCapability` are met by the existing SSN/SOSA classes - in particular `System` and the sub-System mechanism, and `Deployment` and `Platform`. 
I believe that is achievable in principle, but it will also need some work, which is what we discussed in this week's telecon.

**Comment by dr-shorthair** [comment]
BTW - I think the addition of `hasFeatureOfInterest` to `Deployment` is a very good thing. 
It clarifies and reinforces the semantics of `Deployment` very nicely. 
And I really think it addresses the requirements of `ObservingCapability` quite elegantly. 
![Image](https://github.com/user-attachments/assets/47fd170c-5e59-4ee1-b677-85c722072c03)
