### ISSUE TITLE
Change prefLabel of sosa:Sensor to 'Observer'

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#29]
The `Sensor` class is an abstract concept, whose extension includes all agents, devices, software etc that is capable of implementing a procedure in order to evaluate the state of some property. However, the name 'Sensor' is usually only associated with a subset of this conceptual space - i.e. mechanical and electronic sensors. While there is no need to change the URI, it would be helpful and informative to modify the annotation so that users get a better immediate indication of the scope of this class. 

Note that the revision of ISO 19156 currently underway in ISO/TC 211 is adopting many of the innovations from SSN/SOSA/SSN-ext into the UML version of this model. They have already decided to name the corresponding class 'Observer' instead of Sensor.

**Comment by dr-shorthair** [comment]
In #56 it has been resolved that there is no need for a new class `Host` since it is functionally identical to `Platform`. The fact that SOSA Platform implements OMS Host can be indicated through annotation and documentation, and by adding an alternative label 'Host'. 

The case of `Sensor` vs `Observer` is very similar. If people are OK understanding (for example) that humans can be classified as Sensors when they are implementing an observation procedure, then there is no need for a new class. 

On the other hand, if we really wish to enable the creation of a hierarchy of Observer subclasses, with Sensor being the one that we already know about, then having the class Observer could have some utility. However, I'm not sure in practice that any other subclasses are commonly used, or that there are any general differentia to justify a new class? 

This issue did not originally propose a new class, merely that the labeling and documentation could be improved to indicate that SOSA Sensor implements OMS Observer. Perhaps we should just stick with that?

**Comment by dr-shorthair** [comment]
We could also put a `xxx:Observer` class in a SOSA-OMS alignment graph, separate from the SOSA graph. And put the subclass to Sensor axiom there.

**Comment by maximelefrancois86** [comment]
The OMS standard defines "Observer" as: "identifiable entity that **can** generate observations pertaining to an observable property by implementing a procedure"

The **can** here is problematic, as it relates to a capability more than an intrinsic characteristic. 

As a parallel, it would be equivalent to define "Genitor" as: "identifiable entity that **can** generate an offspring" (not talking about the procedure here)

Naively, I would say that "Observer" refers more to the _role_ some entity has with respect to an observation, rather than an intrinsic characteristic of an entity:

- You aren't an observer until you make an observation. 
- A sensor is intrinsically a sensor, but only becomes an observer when it makes an observation.

Therefore to me "observer" would best be used to name an Object Property, such as `sosa:madeByObserver` that would generalize `sosa:madeBySensor`.

**Comment by dr-shorthair** [comment]
`Observer` is the name of the class in OMS. 
However, the definition is essentially the same as `sosa:Sensor`, and there is no separate `Sensor` class in OMS, and thus no subclass relationship. 

So I think we just need to say in the SOSA-OMS mapping that **OMS Observer is implemented by `sosa:Sensor`**. 

The definition of `sosa:Sensor` makes it clear that it is fully general:
> Device, agent (including humans), or software (simulation) involved in, or implementing, a [Procedure](https://www.w3.org/TR/vocab-ssn/#SOSAProcedure). 

Perhaps the appropriate action from this issue is to change the `prefLabel` of `sosa:madeBySensor` to 'made by Observer' ?
