### ISSUE TITLE
Should we merge SSN and SOSA into a single namespace?

### ISSUE THREAD

**Issue by alexrobin** [w3c/sdw-sosa-ssn#48]
The idea would be to define all classes in SOSA, including Deployment, System, etc. that only exist in the SSN namespace as of today.

Even if we do that, we could keep the existing classes in the SSN namespace for backwards compatibility and just map them as equivalent to the new ones we add to SOSA namespace.

What do we do with constraints that are only defined in SSN in the current version?

**Comment by dr-shorthair** [comment]
Currently the SSN graph does two things:
1. declares some less-core classes and properties in a separate namespace (`ssn:` vs `sosa:`) 
2. contains most of the axiomatization

@kjano doesn't want to clutter the SOSA namespace by moving everything into there, so maybe we should still use SSN for the minor classes (to avoid disruption), but then perhaps we should move the axiomatizations into a separate (third) graph? 

The following classes are in the `ssn:` namespace
- ssn:Property
- ssn:Stimulus
- ssn:Input
- ssn:Output
- ssn:System
- ssn:Deployment

**Comment by dr-shorthair** [comment]
[My comment on #56](https://github.com/w3c/sdw-sosa-ssn/issues/56#issuecomment-1709573490) is related. 

In the 2017 formulation we had two graphs, SOSA and SSN. As [mentioned above](https://github.com/w3c/sdw-sosa-ssn/issues/48#issuecomment-1694957463) the SSN graph did two things: 
(i) declared some additional classes and properties, in a separate namespace
(ii) axiomatize the resources from both SOSA and SSN. 

It turns out that having two namespaces was confusing. 
But the modularization of the whole ontology was useful - so we [wrote a paper about it](https://doi.org/10.3233/sw-180320). 

When I developed [SSN-Ext](https://www.w3.org/TR/vocab-ssn-ext/) I separated these concerns. All the new resources were in the SOSA namespace, but they were homed in a new graph. I should also have added the `rdfs:isDefinedBy ssn-ext:` annotation. 

The title of this issue is 'Should we merge SSN and SOSA into a single namespace?'. 
The issue was created by @alexrobin and comments above from @kjano and @maximelefrancois86 appear to concur. 

A potential way forward is 
(i) clone all the existing `ssn:XXX` classes and properties into the `sosa:` namespace, but leave them in the SSN graph;  
(ii) all new resources, including those introduced from SSN-Ext and OMS, should be in the SOSA namespace; 
however
(iii) the new resources can be in various graphs, following the modularization principles. 

What these graphs are should be the subject of separate threads.

**Comment by dr-shorthair** [comment]
To move this forward, I propose to move the resources originating in OMS and SSN-Ext out into separate graphs, so that the SOSA graph reverts back to the 2017 state, and the new materials are in new modules. 

Also see #45

**Comment by rob-metalinkage** [comment]
I'm not in favour of three graphs with sosa namespace.. feels like we are throwing users under the bus to create closures to pay homage to a one time development process.  If changes are non breaking there is not need to separate.  Add a skos:historyNote perhaps if there is a need to extract a sub graph.

**Comment by dr-shorthair** [comment]
OK. Two graphs is the target for "SOSA harmonized with SSN-EXT and OMS": 
1. SOSA graph with names, textual descriptions, and only schema.org annotations and `inverseOf` axioms
2. SSN graph with the full RDFS and OWL axiomatization.

So, for the resources previously sitting in the `ssn:` namespace and SSN graph, can I assume they should be both 
- cloned into the `sosa:` namespace and 
- also added into the SOSA graph (i.e. the sosa.ttl file)

following the patterns described above? 

In which case where should the `owl:equivalentX` axioms sit?
- in the original `ssn:` resources in the SSN graph, or 
- in the axiomatizations of the `sosa:` resources in the SSN graph

**Comment by rob-metalinkage** [comment]
There are three other options:

* in the SOSA graph
* in an alignment graph (sosa-ssn)
* on both ssn: and sosa: resources in the SSN graph

I'd go for the last option:  if people previously cared enough about SSN to use it they will have non-breaking annotations, and if they didnt care about SSN they wont need the axioms anyway.

**Comment by dr-shorthair** [comment]
Need to adjust the spec documentation to reflect the single core namespace

**Comment by dr-shorthair** [comment]
See https://github.com/w3c/sdw-sosa-ssn/commit/d321abec2a115eebed338e733aeb56b8363123f0

**Comment by KathiSchleidt** [comment]
@dr-shorthair sorry for not understanding your process, could you indicate which of the many proposed options you've now implemented?

**Comment by dr-shorthair** [comment]
Just catching up with a dangling issue that was resolved last year - this was all dealt with in e0edbac

**Comment by dr-shorthair** [comment]
@KathiSchleidt Just catching up - this was all dealt with in e0edbac and related changes - the issue should have been closed then. 

See the spec document here: https://w3c.github.io/sdw-sosa-ssn/ssn/#namespaces https://w3c.github.io/sdw-sosa-ssn/ssn/#RDFdistribution and note that core terms are now all in `sosa:` namespace, and all `ssn:` terms in https://github.com/w3c/sdw-sosa-ssn/blob/gh-pages/ssn/integrated/ssn.ttl are marked 'deprecated'.
