### ISSUE TITLE
What's the difference between Platform and Host?

### ISSUE THREAD

**Issue by KathiSchleidt** [w3c/sdw-sosa-ssn#56]
What's the difference conceptually between Platform and Host? To my view, these are two labels for the same concept. I don't see the need for 2 separate concepts within SOSA.

Related to w3c/sdw-sosa-ssn#46

**Comment by dr-shorthair** [comment]
Also discussed extensively in #61

**Comment by dr-shorthair** [comment]
@kjano asked:

> I would be very thankful if somebody could clarify why all these
concepts that have been deliberately excluded from SOSA would have to be
included within SOSA and not a module and what the intended process for
this is.

Do you mean 
(i) deliberately excluded from the SOSA _graph_ (i.e. tagged `rdfs:isDefinedBy sosa:` and appearing in the sosa.ttl file) or 
(ii) deliberately excluded from the SOSA _namespace_ ? 

My reading of #48 is that the judgement is that it has been unhelpful and confusing to have concepts for SSN and SOSA in more than one namespace, because it means that designers and developers always have to check which namespace everything is in (this has certainly been my experience!). So new resources should all be in the SOSA namespace (which is what I did in ssn-ext). 

On the other hand this does not necessarily imply that all these resources must be the SOSA graph, `rdfs:isDefinedBy sosa:` and declared in sosa.ttl. 

As I understand it, these concerns are separable - we can remove the namespace confusion, but retain the graph modularity. 

Is that what you mean @kjano ?

**Comment by KathiSchleidt** [comment]
Agreement:
Remove sosa:Host
Align with sosa:Platform with OMS:Host

Open: how to reference OMS:Host: use OGC Modspec

**Comment by rob-metalinkage** [comment]
From the rolling minutes https://docs.google.com/document/d/15TBmYhgRjncdd_bvmTKygCD8aIhQo1-Tkg3eOKjYNTw/edit?pli=1 ,  the decision:

Decided we need to have a consistent approach to referencing OMS to address issues of transparency, a PR to remove OMS  “Host” as a class and replace with a reference to the OMS usage/terminology can be used to test the pattern with the wider audience. 

Action: RA to generate a PR with a proposal for referencing OMS conformance classes and show alternative labels.  This will then free up group to remove sosa:Host as an unnecessary synonym.
