### ISSUE TITLE
Document the alignment of SOSA with OMS on a class-by-class basis

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/sdw-sosa-ssn#57]
Use a uniform method to document SOSA-OMS alignments within the machine-readable artefacts (i.e. the RDFS/OWL).

**Comment by dr-shorthair** [comment]
Here are three (nine?) options for a potential approach: 
https://github.com/w3c/sdw-sosa-ssn/blob/247a0dc1b3a5ab86ce8f9f1e86384a473141b242/ssn/integrated/sosa.ttl#L437-L439 

As well as choosing a suitable predicate for the link, we need to understand which of these three potential requirements from the UML models (concept, core, basic) is actually being implemented here.

**Comment by dr-shorthair** [comment]
@Jano suggests that OGC/ISO should coin its own alignment axioms, with sub- or super-property relationships to the common vocabs to support inferencing.

@sgrellet suggests that the mappings should always be to the conceptual model.

**Comment by sgrellet** [comment]
on where to point to in oms I'd suggest the following sequence
1°/ point to oms-bs-cpt -> Conceptual model
2°/ point to oms-obs-core -> Abstract model, only when a 'class' appears for the 1st time (= not present at conceptual level)
3°/ not use basic because 'basic' intent is to have a 'ready to roll' UML implementation of OMS and should not create new semantic artefact

And apply the same logic for the Sample part

**Comment by dr-shorthair** [comment]
See #104 for completed version of SOSA-OMS graph with explicit mappings.

**Comment by dr-shorthair** [comment]
See #116
